stages:
- test
- name: deploy
  if: tag IS present

language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'

install: pip install tox coveralls
script: tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
after_success: coveralls

jobs:
  include:
  - stage: deploy
    install: skip
    script: skip
    deploy:
      stage: deploy
      provider: pypi
      on:
        tags: true
      distributions: sdist bdist_wheel
      user: IamShobe
      password:
        secure: "iQt70CmOKzteB1wtoQp7BhYWJA0WuPwn9NoEC1CUIGNtUPNtOU4FrdNMEtvf9oC2OFP2Y+G+3iXuMX3/+Nlwa568n+vFhu5ND9Wjdt4SsbdTfTeUTUEb41lnLIq4c+qpfuObPumqpNGMLE9iEkc4OKlYd3F6U5MYpVCkcNjmaVNkaoQeS7yC0GYL3glJIu1EzS8fZ2jj5JVk5ifEnMov6l5Ks2e4mLiI0A2w6mpTvOlITdzA1mQ1uRkx8bpjuaqLB6tAHxNRmMHETrrD59WanQvNYlf+Yy5YktkflIBL4IlMkfJXJPfhtNLoWpsNYCxhrK2DJtioutH5xDRChvesdGmXn43zpmnjyKt5JK4bCb5N9GYZM8AoEMJcV56qivpksU3h4bwyU3AqkN7Dy3JKCvGfNgD4FTISlL/YBInNWdOeNHRhA29xjDmZNnYOnl+4nPzpBxp7vGPgnjE+Qjk6CsOTRkn/+XWZscdKArlBCxw8Uu+marqDNrMxyCKVUzEYso5oKriRz0SV6j1SqzHrfyqHbq3P/ZcywoSPMRWuSna7Q2N60GZVgX/dX1yta+lx1iymqpdjJbc6dCaRV0AAwOTgxXvJxfdphtKwa8TMYGTGpk1uFAqF/Jr9z7UXmHWXiAcguYJgZEQfVbqurpD22l5JF6Shp6ZsFP52Rhgbb0Y="